<?php

namespace AppBundle\Repository;

/**
 * commentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentairesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllComment($id)
    {
        return $this->createQueryBuilder('p')
           ->where('p.idarticle LIKE :idart')
            ->andWhere('p.isvalid = 1')
            ->setParameter('idart',$id)
            ->getQuery()->getArrayResult();
    }
}
